import type { IndustryAnchor, LevelDefinition, StageMeta } from "./types";

export const levels: LevelDefinition[] = [
  { level: 0, title: "初识 AI", role: "AI 入门者", stage: "起步", definition: "了解 AI 基本概念，知道什么是大语言模型，准备开始使用 AI 工具提升工作效率。", standard: "完成首次 AI 对话体验", abilities: ["了解 AI 基本概念", "知道主流大模型", "完成首次对话"], criteria: [{ id: "first-chat", label: "完成首次 AI 对话", evidenceHint: "截图或记录" }, { id: "understand-ai", label: "了解 AI 能做什么", evidenceHint: "简要笔记" }, { id: "setup-tool", label: "完成工具环境搭建", evidenceHint: "工具截图" }], practices: ["注册并体验千问对话", "了解 AI 应用场景"], path: "注册千问账号，完成第一次对话体验，了解 AI 能帮你做什么。", resources: [{ label: "千问官网", url: "https://qianwen.aliyun.com/" }] },
  { level: 1, title: "开口会问", role: "AI 对话者", stage: "会用 AI", definition: "能与主流 C 端智能体有效对话，在严肃工作场景中获得可用输出，并了解 Qwen 模型家族。", standard: "完成 3 类真实工作任务", abilities: ["结构化提示词", "追问、拆解与自查", "模型选型", "理解幻觉与上下文"], criteria: [{ id: "task-3", label: "完成 3 类真实任务", evidenceHint: "提交任务前后对比与最终产出" }, { id: "qwen-map", label: "讲清 Qwen 家族选型", evidenceHint: "模型选型速查表或讲解记录" }, { id: "quality", label: "能迭代输出质量", evidenceHint: "至少 1 组提示词迭代记录" }], practices: ["会议纪要待办提取", "竞品资料速读", "周报初稿生成"], path: "连续 1 周每天用 AI 处理真实工作，同题对比提示词迭代前后的效果。", resources: [{ label: "Qwen 官方文档", url: "https://qwen.readthedocs.io/zh-cn/latest/" }, { label: "提示工程指南", url: "https://www.promptingguide.ai/zh" }] },
  { level: 2, title: "问以致用", role: "智能体操作者", stage: "会用 AI", definition: "熟练使用千问办公等通用智能体，掌握工作空间、定时任务和 Skill 基础。", standard: "2 个每周使用 ≥2 次的常态化应用", abilities: ["工作空间与文件管理", "配置定时任务", "组合 Skill", "理解 Agent 与 Chat"], criteria: [{ id: "routine-2", label: "跑通 2 个常态化应用", evidenceHint: "连续两周运行记录" }, { id: "workflow", label: "独立配置工作流", evidenceHint: "配置说明、截图或演示" }, { id: "business", label: "绑定真实工作场景", evidenceHint: "说明节省时间或提升质量" }], practices: ["客户拜访前情报汇总", "标书条款提取", "POC 报告整理"], path: "盘点每周重复工作，亲手搭建 2 个任务或 Skill 工作流并持续运行 2 周。", resources: [{ label: "钉钉开放平台", url: "https://open.dingtalk.com/document/" }] },
  { level: 3, title: "对客答问", role: "客户面前的演示者", stage: "会用 AI", definition: "能独立向客户汇报千问办公，针对客户需求编写 Skill，并在现场完成演示。", standard: "客户现场演示 + 定制 Skill + 故障兜底", abilities: ["产品价值与报价逻辑", "Skill 需求拆解与调试", "现场演示", "故障预案"], criteria: [{ id: "demo", label: "完成真实客户现场演示", evidenceHint: "议程、演示记录与客户反馈" }, { id: "skill", label: "交付 1 个客户定制 Skill", evidenceHint: "脱敏说明与运行结果" }, { id: "fallback", label: "具备演示兜底方案", evidenceHint: "故障预案与复盘" }], practices: ["真实客户现场演示", "客户需求定制 Skill", "产品汇报试讲"], path: "把日常工作迁移到千问办公；复刻团队 Skill 后再独立编写 3 个。", resources: [{ label: "Qwen-Agent", url: "https://github.com/QwenLM/Qwen-Agent" }] },
  { level: 4, title: "博问众长", role: "顶尖工具驾驭者", stage: "会建 AI", definition: "使用年度工具目录中的先进桌面智能体和模型形成一手体感，能部署优质项目并接入 dws。", standard: "部署 3 个项目（必含 dws）+ 真实任务对比", abilities: ["多模型真实对比", "Git 与 GitHub", "部署与排障", "dws 接入"], criteria: [{ id: "compare", label: "完成真实任务多模型对比", evidenceHint: "同题结果、判断与适用边界" }, { id: "projects", label: "部署 3 个业务相关项目", evidenceHint: "仓库、运行记录与问题复盘" }, { id: "dws", label: "完成 dws 智能体实践", evidenceHint: "自动化过程与业务效果" }], practices: ["dws 办公自动化实践", "3 个行业相关开源项目", "模型真实场景对比报告"], path: "用真实任务同题多模型对比；每周部署 1 个项目，三周积累 3 个。", resources: [{ label: "Pro Git 中文版", url: "https://git-scm.com/book/zh/v2" }, { label: "dws 仓库", url: "https://github.com/DingTalk-Real-AI/dingtalk-workspace-cli" }] },
  { level: 5, title: "问需而造", role: "售前原型开发者", stage: "会建 AI", definition: "具备 AI Coding 能力，能独立开发客户场景高保真原型，并形成精准竞品观点。", standard: "2 个原型进入售前 + 1 个精准竞品观点", abilities: ["AI Coding 全流程", "通用智能体架构", "竞品分析", "快速交付 Demo"], criteria: [{ id: "prototype-2", label: "2 个原型进入真实售前", evidenceHint: "演示链接、商机关联与反馈" }, { id: "feedback", label: "至少 1 次客户正反馈", evidenceHint: "脱敏会议纪要或反馈记录" }, { id: "competitive", label: "形成证据化竞品观点", evidenceHint: "实测数据与结论" }], practices: ["真实售前原型", "客户明确正反馈", "证据支撑的竞品分析"], path: "连续 4 周每周复刻 1 个客户场景 Demo，并主动认领商机原型。", badges: ["售前原型", "智能体架构"], resources: [{ label: "Building Effective Agents", url: "https://www.anthropic.com/research/building-effective-agents" }, { label: "MCP 官网", url: "https://modelcontextprotocol.io/" }] },
  { level: 6, title: "问一知十", role: "资产沉淀与提效者", stage: "会建 AI", definition: "把个人经验建成知识库与 Skill，量化提效并沉淀为可横向复用的组织资产。", standard: "团队复用 ≥6 人 / 客户 ≥2 家 / 治理试点 ≥1 家", abilities: ["知识资产化", "Before / After 量化", "低成本复用", "知识治理"], criteria: [{ id: "asset", label: "资产通过合规审核并入库", evidenceHint: "资产库记录与审核结论" }, { id: "reuse", label: "达到复用门槛之一", evidenceHint: "使用记录、客户记录或试点报告" }, { id: "impact", label: "量化 Before / After", evidenceHint: "时间、质量或成本变化" }], practices: ["发布团队公共仓库", "邀请同事试用迭代", "完成知识治理全流程"], path: "盘点 3 项高频工作逐个资产化，记录提效数据，打磨到他人拿来即用。", badges: ["知识资产", "知识治理"], resources: [{ label: "阿里云百炼知识库", url: "https://help.aliyun.com/zh/model-studio/" }, { label: "LlamaIndex", url: "https://docs.llamaindex.ai/" }] },
  { level: 7, title: "问诊寻因", role: "架构诊断与集成专家", stage: "会解 AI", definition: "能基于 trace 定位并解决智能体问题，通过 Skill / MCP 连接客户业务系统。", standard: "集成 POC ≥1 + 一线问题 ≥3", abilities: ["智能体 trace 分析", "MCP / API 集成", "鉴权与安全", "AI 信息雷达"], criteria: [{ id: "poc", label: "完成客户测试环境集成 POC", evidenceHint: "架构、结果与客户确认" }, { id: "cases", label: "解决 3 个一线问题", evidenceHint: "trace、根因与修复记录" }, { id: "security", label: "完成安全边界说明", evidenceHint: "鉴权、数据与合规设计" }], practices: ["客户测试环境 POC", "诊断案例库", "最新 AI 成果客户交流"], path: "主动认领 trace 问题，积累诊断案例；在本地先完成 1 次系统对接。", badges: ["集成诊断", "MCP 工程"], resources: [{ label: "MCP 协议规范", url: "https://modelcontextprotocol.io/specification" }, { label: "钉钉 API", url: "https://open.dingtalk.com/document/" }] },
  { level: 8, title: "寻根问底", role: "评测与交付专家", stage: "会解 AI", definition: "在评测工程、全栈交付、后训练咨询中主修一项、辅修一项，直接支撑客户决策与真实交付。", standard: "主修徽章 1 枚 + 辅修徽章 1 枚 + 真实业务结果", abilities: ["定制评测工程", "全生命周期交付", "技术选型支撑", "后训练咨询"], criteria: [{ id: "major", label: "完成 1 个主修专业徽章", evidenceHint: "评测、交付或后训练完整案例" }, { id: "minor", label: "完成 1 个辅修专业徽章", evidenceHint: "可验证的辅助案例" }, { id: "outcome", label: "产生真实业务结果", evidenceHint: "商机、客户决策或稳定使用记录" }], practices: ["复现公开评测", "客户场景评测集", "真实应用稳定运行满月"], path: "选择最贴合岗位的主修方向，完成真实项目；再补齐一项辅助能力。", badges: ["评测工程", "全栈交付", "后训练咨询"], resources: [{ label: "OpenCompass", url: "https://github.com/open-compass/opencompass" }, { label: "Hugging Face 课程", url: "https://huggingface.co/learn" }] },
  { level: 9, title: "业界来问", role: "组织影响力构建者", stage: "会解 AI", definition: "在细分领域形成头部实践，通过组织复用、行业影响或关键客户突破获得认证。", standard: "组织复用 / 外部影响 / 客户突破满足其一并可归因", abilities: ["细分领域头部实践", "原创内容生产", "组织影响", "客户高层突破"], criteria: [{ id: "original", label: "具备一手原创实践", evidenceHint: "持续项目或内容记录" }, { id: "reach", label: "达到一项影响力门槛", evidenceHint: "组织使用、开源或平台数据" }, { id: "attribution", label: "个人贡献可归因", evidenceHint: "负责人确认与贡献说明" }], practices: ["持续迭代开源项目", "固定节奏对外输出", "以行业专家身份参与项目"], path: "选择有一手实践的细分方向持续深耕，用真实反馈迭代内容与工具。", resources: [{ label: "GitHub", url: "https://github.com/" }] },
  { level: 10, title: "问以致胜", role: "AI 商业价值领航者", stage: "会赢 AI", definition: "用 AI 加较少资源解决行业挑战性问题，改变成本或价值结构并形成可复制商业价值。", standard: "AI ARR ≥1000 万 + 明确复制窗口", abilities: ["行业问题定义", "AI 杠杆解法", "商业价值闭环", "规模化复制"], criteria: [{ id: "arr", label: "商业结果达到认证门槛", evidenceHint: "经确认的 ARR 与个人贡献" }, { id: "playbook", label: "形成可复制方法论", evidenceHint: "标准方案、成本与交付边界" }, { id: "pipeline", label: "识别至少 3 个复制目标", evidenceHint: "同类客户清单与推进状态" }], practices: ["沉淀可复制方法论", "识别同类客户", "降低复制边际成本"], path: "在真实商机中打出来：首单跑通后即刻沉淀方法论并开启同类客户复制。", resources: [] },
];

export const stageMeta: StageMeta[] = [
  { label: "会用 AI", range: "L0–L3", color: "#3977f6", copy: "全员通用" },
  { label: "会建 AI", range: "L4–L6", color: "#7c5ce5", copy: "岗位主赛道" },
  { label: "会解 AI", range: "L7–L9", color: "#e17a37", copy: "专家纵深" },
  { label: "会赢 AI", range: "L10", color: "#159b76", copy: "商业价值" },
];

export const industryAnchors: IndustryAnchor[] = [
  { name: "高校", owner: "高校行业线", version: "2026 Q3", items: [{ level: 3, title: "AI 助研 / 智慧教务演示", template: "客户演示包" }, { level: 5, title: "科研文献分析原型", template: "原型需求模板" }, { level: 6, title: "高校标书模板库", template: "资产入库清单" }, { level: 7, title: "对接教务系统", template: "集成 POC 清单" }] },
  { name: "新质", owner: "新质行业线", version: "2026 Q3", items: [{ level: 3, title: "研发提效演示", template: "客户演示包" }, { level: 5, title: "工艺知识问答原型", template: "原型需求模板" }, { level: 6, title: "芯片行业术语知识库", template: "资产入库清单" }, { level: 7, title: "对接 PLM / MES", template: "集成 POC 清单" }] },
  { name: "能源", owner: "能源行业线", version: "2026 Q3", items: [{ level: 3, title: "巡检报告 / 规程问答", template: "客户演示包" }, { level: 5, title: "生产日报原型", template: "原型需求模板" }, { level: 6, title: "安全合规知识库", template: "资产入库清单" }, { level: 7, title: "对接调度 / EAM", template: "集成 POC 清单" }] },
  { name: "政务", owner: "政务行业线", version: "2026 Q3", items: [{ level: 3, title: "公文辅助 / 政策问答", template: "客户演示包" }, { level: 5, title: "12345 工单分派", template: "原型需求模板" }, { level: 6, title: "信创适配经验库", template: "资产入库清单" }, { level: 7, title: "对接政务 OA", template: "集成 POC 清单" }] },
];
